# Generated by Django 2.2.5 on 2019-11-24 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WhereIs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServidorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('dominio', models.CharField(blank=True, max_length=50)),
                ('repositorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WhereIs.RepositorioModel')),
            ],
        ),
    ]
