# Generated by Django 2.2.5 on 2019-11-24 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WhereIs', '0002_servidormodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidormodel',
            name='repositorio',
        ),
        migrations.AddField(
            model_name='repositoriomodel',
            name='servidor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='WhereIs.ServidorModel'),
            preserve_default=False,
        ),
    ]
