# Generated by Django 2.2.5 on 2019-11-24 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WhereIs', '0003_auto_20191124_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoriomodel',
            name='servidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WhereIs.ServidorModel'),
        ),
    ]
