# Generated by Django 2.2.5 on 2019-11-24 21:51

import WhereIs.models._validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhereIs', '0004_auto_20191124_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidormodel',
            name='ip',
            field=models.CharField(max_length=16, validators=[WhereIs.models._validators.validate_ip]),
        ),
    ]
